package Modelos;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Profesor.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Profesor implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** IdProfesor. */
	private Integer idprofesor;

	/** NIP_P. */
	private String nipP;

	/** Nombre. */
	private String nombre;

	/** Especialidad. */
	private String especialidad;

	/** Telefono. */
	private String telefono;

	/** The set of Asignatura. */
	private Set<Asignatura> asignaturaSet;

	/**
	 * Constructor.
	 */
	public Profesor() {
		this.asignaturaSet = new HashSet<Asignatura>();
	}

	/**
	 * Set the IdProfesor.
	 * 
	 * @param idprofesor
	 *            IdProfesor
	 */
	public void setIdprofesor(Integer idprofesor) {
		this.idprofesor = idprofesor;
	}

	/**
	 * Get the IdProfesor.
	 * 
	 * @return IdProfesor
	 */
	public Integer getIdprofesor() {
		return this.idprofesor;
	}

	/**
	 * Set the NIP_P.
	 * 
	 * @param nipP
	 *            NIP_P
	 */
	public void setNipP(String nipP) {
		this.nipP = nipP;
	}

	/**
	 * Get the NIP_P.
	 * 
	 * @return NIP_P
	 */
	public String getNipP() {
		return this.nipP;
	}

	/**
	 * Set the Nombre.
	 * 
	 * @param nombre
	 *            Nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the Nombre.
	 * 
	 * @return Nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the Especialidad.
	 * 
	 * @param especialidad
	 *            Especialidad
	 */
	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	/**
	 * Get the Especialidad.
	 * 
	 * @return Especialidad
	 */
	public String getEspecialidad() {
		return this.especialidad;
	}

	/**
	 * Set the Telefono.
	 * 
	 * @param telefono
	 *            Telefono
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * Get the Telefono.
	 * 
	 * @return Telefono
	 */
	public String getTelefono() {
		return this.telefono;
	}

	/**
	 * Set the set of the Asignatura.
	 * 
	 * @param asignaturaSet
	 *            The set of Asignatura
	 */
	public void setAsignaturaSet(Set<Asignatura> asignaturaSet) {
		this.asignaturaSet = asignaturaSet;
	}

	/**
	 * Add the Asignatura.
	 * 
	 * @param asignatura
	 *            Asignatura
	 */
	public void addAsignatura(Asignatura asignatura) {
		this.asignaturaSet.add(asignatura);
	}

	/**
	 * Get the set of the Asignatura.
	 * 
	 * @return The set of Asignatura
	 */
	public Set<Asignatura> getAsignaturaSet() {
		return this.asignaturaSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idprofesor == null) ? 0 : idprofesor.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Profesor other = (Profesor) obj;
		if (idprofesor == null) {
			if (other.idprofesor != null) {
				return false;
			}
		} else if (!idprofesor.equals(other.idprofesor)) {
			return false;
		}
		return true;
	}

}
