package Modelos;

import java.io.Serializable;

/**
 * Model class of Recibe.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Recibe implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Alumno. */
	private Alumno alumno;

	/** Asignatura. */
	private Asignatura asignatura;

	/** cursoEscolar. */
	private String cursoescolar;

	/**
	 * Constructor.
	 */
	public Recibe() {
	}

	/**
	 * Set the Alumno.
	 * 
	 * @param alumno
	 *            Alumno
	 */
	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	/**
	 * Get the Alumno.
	 * 
	 * @return Alumno
	 */
	public Alumno getAlumno() {
		return this.alumno;
	}

	/**
	 * Set the Asignatura.
	 * 
	 * @param asignatura
	 *            Asignatura
	 */
	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	/**
	 * Get the Asignatura.
	 * 
	 * @return Asignatura
	 */
	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	/**
	 * Set the cursoEscolar.
	 * 
	 * @param cursoescolar
	 *            cursoEscolar
	 */
	public void setCursoescolar(String cursoescolar) {
		this.cursoescolar = cursoescolar;
	}

	/**
	 * Get the cursoEscolar.
	 * 
	 * @return cursoEscolar
	 */
	public String getCursoescolar() {
		return this.cursoescolar;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((alumno == null) ? 0 : alumno.hashCode());
		result = prime * result + ((asignatura == null) ? 0 : asignatura.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Recibe other = (Recibe) obj;
		if (alumno == null) {
			if (other.alumno != null) {
				return false;
			}
		} else if (!alumno.equals(other.alumno)) {
			return false;
		}
		if (asignatura == null) {
			if (other.asignatura != null) {
				return false;
			}
		} else if (!asignatura.equals(other.asignatura)) {
			return false;
		}
		return true;
	}

}
